config/routes.rb
Rails.application.routes.draw do
  root 'dogtest#index'
  get 'dogs/:id/' => 'dogtest#show', as: :dog

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_many :eyes

end

app/models/eye.rb
class Eye < ActiveRecord::Base
  belongs_to :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogtest_controller.rb
class DogtestController < ApplicationController
  def index
    @dogs = Dog.all
  end
  def show
    @dog = Dog.find(params[:id])
    @eyes = @dog.eyes
  end
















end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogtest_helper.rb
module DogtestHelper
end

app/views/dogtest/index.html.erb
<div id = "welcome part">
  <h1> Welcome to my Website </h1>

  <div id = "list all dogs">
    <% @dogs.each do |t| %>
      <h2><%= t.name %><br>
        <%= t.color %><br>
        <%= t.id%><br>
      <%= link_to "description", dog_path(t)%> </h2>


    <% end %>

  </div>


</div>

app/views/dogtest/show.html.erb
<div id = "show_view">

  <h2> <%= @dog.name %> </h2><br>


  <% @eyes.each do |t| %>
    <%= label_tag t.color %>
  <% end %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppingtut</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>